### ISSUE TITLE
Python Script

### ISSUE THREAD

**Issue by ghost** [guidezpl/Set-Folder-Cover#1]
How much does `setIcon.py` script actually play into the overall program? I see that you imported some modueles but as someone who does not write in Python, I don't know how significant they are.

By asking this question, too, I'm looking to find out if I could make this work without Python and test to see if `setCovers` is cross-platform (so that it's easy for the average person to use without installing anything).

**Comment by guidezpl** [comment]
setIcon could be better named setIconOSX because it's the cleanest method I could find to set a folder's icon on OSX. Everything else should work cross-platform

**Comment by ghost** [comment]
@guidezpl There are multiple references to the Python script in the shell file. 
So wouldn't this entire repository be limited to just OSX or Unix devices?
